image:
  repository: cr.yandex/crp8nsgoqk70ro4v6c1p/back
  tag: "01"
  pullPolicy: IfNotPresent

imagePullSecrets: "yc-registry-key"

service:
  port: 8081

envSecrets:
  POSTGRES_HOST: ${env_POSTGRES_HOST}
  POSTGRES_PORT: ${env_POSTGRES_PORT}
  POSTGRES_USER: ${env_POSTGRES_USER}
  POSTGRES_PASSWORD: ${env_POSTGRES_PASSWORD}
  POSTGRES_DB: ${env_POSTGRES_DB}
  REDIS_HOST: ${env_REDIS_HOST}
  REDIS_PORT: ${env_REDIS_PORT}
  REDIS_PASSWORD: ${env_REDIS_PASSWORD}
  FLUENTD_ENABLED: ${env_FLUENTD_ENABLED}
  FLUENTD_HOST: ${env_FLUENTD_HOST}
  FLUENTD_PORT: ${env_FLUENTD_PORT}
  SERVER_PORT: ${env_SERVER_PORT}
  DEBUG: ${env_DEBUG}
